### ISSUE TITLE
[NOT FIXED] | b95 | ScaffoldWalk1 | Private Client

### ISSUE THREAD

**Issue by FaulheitDev** [hamaplay/titanAC#2]
Module: **Scaffold**
Sneak: true
Delay: 4.0

SRC:

nah****

**Comment by hamaplay** [comment]
ScaffoldWalk Update is included in latest Update. As long the scaffold needs to activate sneak, the issue will probably not be fixxed. (maybe later anytime?)

**Comment by FaulheitDev** [comment]
but its very fast

**Comment by hamaplay** [comment]
See issue #4 (my reply). Should explain it

**Comment by hamaplay** [comment]
-> reopened

**Comment by hamaplay** [comment]
Done
