### ISSUE TITLE
Speed - bypass

### ISSUE THREAD

**Issue by twcrnr** [hamaplay/titanAC#5]
Bypass: Speed
Bypass beschreibung: Durch ein "backtimer" - module wird der Speed ermöglicht
Client: `ItZuNa` `b2.5`
src/settings: 
	public void titan() {
		mc.thePlayer.setSprinting(true);
		if(mc.thePlayer.onGround) {
			if(mc.thePlayer.moveForward != 0 || mc.thePlayer.moveStrafing != 0) {
			mc.thePlayer.jump();
			}
		} else {
			mc.thePlayer.jumpMovementFactor = 0.04F;
			mc.timer.timerSpeed = 0.8F;
			mc.thePlayer.landMovementFactor = 0.5F;
			mc.thePlayer.moveStrafing *= 0.2F;
		}
	}

**Comment by hamaplay** [comment]
Ist der Speed schneller als ein legit? Timer 0.8diff scheint den Spieler stark zu verlangsamen.
PS: backwards-diff Timer ist auf latest in betracht gepatcht
