### ISSUE TITLE
Boost/  1/² NCP-hop - Bypass

### ISSUE THREAD

**Issue by twcrnr** [hamaplay/titanAC#6]
Bypass: Boost / 1/² NCP-hop
Bypass: siehe src
Client: `ItZuNa` `b2.5`
src/settings:
	public void titan() {
		if(mc.thePlayer.onGround) {
			if(mc.gameSettings.keyBindAttack.isKeyDown()) {
				mc.thePlayer.jump();
				mc.thePlayer.motionX *= 1F;
				mc.thePlayer.motionZ *= 1F;
			}
		}
		mc.thePlayer.motionY = -0.5F;
	}

**Comment by hamaplay** [comment]
Notiert. Da der bHop nicht allzu schnell wirkt, wird er vom repMovBehaviour-Checkutil auf der latest gepatcht sein.
