### ISSUE TITLE
Tower - Bypass

### ISSUE THREAD

**Issue by twcrnr** [hamaplay/titanAC#7]
Bypass: Tower
Bypass beschreibung: siehe src
Client: `ItZuNa` `b2.5` 
src/settings:
	public void titan() {
		if (mc.gameSettings.keyBindUseItem.isKeyDown()) {
			if (mc.thePlayer.onGround) {
				mc.timer.timerSpeed = 2F;
				mc.thePlayer.jump();
				mc.rightClickDelayTimer = 1;
			}
		} else {
			mc.timer.timerSpeed = 1F;
		}
	}

// oder //
	public void rewi2() {
		Item item = mc.thePlayer.getCurrentEquippedItem().getItem();
		if ((item instanceof ItemBlock)) {
			if (mc.thePlayer.onGround) {
				if (mc.gameSettings.keyBindUseItem.isKeyDown()) {
					mc.thePlayer.jump();
					mc.rightClickDelayTimer = 1;
					mc.timer.timerSpeed = 0.5F;
				} else {
				}
			} else {
				if(mc.gameSettings.keyBindUseItem.getIsKeyPressed()) {
					mc.timer.timerSpeed = 2F;
				}else {
					mc.timer.timerSpeed = 1F;
				}
			}
		}else {
			if(mc.gameSettings.keyBindUseItem.isKeyDown()) {
				mc.timer.timerSpeed = 1F;
			}else {
				mc.timer.timerSpeed = 1F;
			}
		}
	}

**Comment by hamaplay** [comment]
Building Checks sind aufgrund eines fehlenden Utils nicht vollständig funktionsfähig. Latest sollte den Fehler beheben.
