### ISSUE TITLE
SlowMode - Bypass

### ISSUE THREAD

**Issue by twcrnr** [hamaplay/titanAC#8]
Bypass: SlowMode
Bypass beschreibung: siehe src
Client: `ItZuNa` `b2.5`
src/settings: 
	public void titan() {
		if(mc.gameSettings.keyBindUseItem.isKeyDown()) {
			mc.timer.timerSpeed = 0.2F;
		} else {
			mc.timer.timerSpeed = 1F;
		}

**Comment by hamaplay** [comment]
Backwards-Timerdiffs sind auf der latest silent behoben, jedoch nicht auf vollständigen setback ausgelegt.
