### ISSUE TITLE
ChestStealer - bypass

### ISSUE THREAD

**Issue by twcrnr** [hamaplay/titanAC#9]
Bypass: ChestStealer
Bypass beschreibung: siehe src 
Client: `ItZuNa` `b2.5`
src/settings:
	public void onUpdate(EventUpdate eventUpdate) {
		if ((this.mc.thePlayer.openContainer != null) && (this.mc.thePlayer.openContainer instanceof ContainerChest)) {
			ContainerChest chest = (ContainerChest) this.mc.thePlayer.openContainer;
			for (int i = 0; i < chest.getLowerChestInventory().getSizeInventory(); i++) {
				if ((chest.getLowerChestInventory().getStackInSlot(i) != null) && (this.time.hasReached(170l))) {
					this.mc.playerController.windowClick(chest.windowId, i, 0, 1, this.mc.thePlayer);
					this.time.reset();
				}
			}

			if (chest.getInventory().isEmpty()) {
				this.mc.displayGuiScreen(null);
			}

		}
	}

**Comment by hamaplay** [comment]
Für b97 notiert. -> Überarbeitung von ItemClickBehavior p/72 und p/31.
